package main

const (
	SUPPER_BLOCK_MAGIC_SIZE = 4
	SUPPER_BLOCK_VER_SIZE = 1
	SUPPER_BLOCK_PADDING_SIZE = 3

	NEEDLE_HEADER_MAGIC_SIZE = 4
	NEEDLE_COOKIE_SIZE       = 4
	NEEDLE_KEY_SIZE          = 8
	NEEDLE_FLAG_SIZE         = 1
	NEEDLE_DATA_SIZE         = 4
	NEEDLE_FOOTER_MAGIC_SIZE = 4
	NEEDLE_CHECKSUM_SIZE     = 4

)

const (
	SUPPER_BLOCK_MAGIC_STR = "[0xAB 0xCD 0xEF 0x00]"
	SUPPER_BLOCK_VER_STR = "[0x01]"
	SUPPER_BLOCK_PADDING_STR = "[0x00 0x00 0x00]"

	NEEDLE_HEADER_MAGIC_STR = "[0x12 0x34 0x56 0x78]"
	NEEDLE_FOOTER_MAGIC_STR = "[0x87 0x65 0x43 0x21]"
)
