PprofEnable = true

PprofListen = "localhost:2231"

HttpAddr = "localhost:2232"

BfsAddr = "localhost:2235"

Domain = "http://localhost:2232/"                                                                              

Prefix = "/bfs/"

MaxFileSize = 20971520

AliyunKeyId = "xxxxx"
AliyunKeySecret = "xxxxx"

NetUserName = "xxxx"
NetPasswd = "xxxx"

PurgeMaxSize = 100000
